
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      TZ: "Asia/Tokyo"
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./certs:/etc/certs
    networks:
      - gitlab
    depends_on:
      - db

  # runner:
  #   container_name: runner
  #   image: gitlab/gitlab-runner:latest
  #   hostname: ${GITLAB_HOSTNAME}
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   restart: always
  #   # volumes:
  #   #   - git/runner-config:/etc/gitlab-runner
  #   #   - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - gitlab
  #   depends_on:
  #     - gitlab

  db:
    container_name: db
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: gitlab
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - gitlab
    volumes:
      - db:/var/lib/postgresql/data

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt

volumes:
  db:
  # config:
  # runner-config:
  # logs:
  # data:

networks:
  gitlab:
