
services:
  gitlab:
    build: ./gitlab
    restart: always
    hostname: gitlab.local
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Tokyo"
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_host'] = 'db'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'n7K.~H(*aSa.kPNz'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    depends_on:
      - db

  runner:
    build: ./gitlab-runner
    hostname: gitlab.local
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
  
  db:
    build: ./db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: n7K.~H(*aSa.kPNz
      POSTGRES_DB: gitlab
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  config:
  runner-config:
  logs:
  data:
