version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: ubuntu-gitlab.local
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    # shm_size: '256m'
    environment:
      TZ: "Asia/Tokyo"
      GITLAB_OMNIBUS_CONFIG: |
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/server.csr"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/server.key"
      # "from_file('/omnibus_config.rb')"
    # configs:
    #   - source: gitlab
    #     target: /omnibus_config.rb
    # secrets:
    #   - gitlab_root_password
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine
  #   hostname: ubuntu-gitlab.local
  #   deploy:
  #     mode: replicated
  #     replicas: 4
  #   restart: always
  #   volumes:
  #     - ./gitlab-runner/config:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock

# configs:
#   gitlab:
#     file: ./gitlab.rb

# secrets:
#   gitlab_root_password:
#     file: ./root_password.txt
