
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    expose:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      TZ: "Asia/Tokyo"
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: config
        target: /omnibus_config.rb
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl
    depends_on:
      - db

  runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      mode: replicated
      replicas: 4
    restart: always
    volumes:
      - ./gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/ssl
    depends_on:
      - gitlab

  db:
    container_name: db
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: gitlab
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

configs:
  config:
    file: ./gitlab.rb

volumes:
  db:
